
import com.restfb.BinaryAttachment;
import com.restfb.DefaultFacebookClient;
import com.restfb.FacebookClient;
import com.restfb.FacebookClient.AccessToken;
import com.restfb.Parameter;
import com.restfb.types.FacebookType;
import com.restfb.types.User;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author saulo
 */
public class MainJFrame extends javax.swing.JFrame {

    String csvFile = "";
    String line = "";
    String cvsSplitBy = ",";
    String cidade = "";

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Facebook UserToken:");

        jTextField1.setEditable(false);

        jToggleButton1.setText("Caregar Arquivo");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Gerar Graficos");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome da Cidade/Região:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Desafio POO - PostDatasFB");

        jToggleButton3.setText("Fazer Postagem");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Mensagem:");

        jLabel5.setText("UserID:");

        jLabel6.setText("Legenda da Tag:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Marcar Usuario:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Facebook Post:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(404, 404, 404))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addComponent(jToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addComponent(jToggleButton3)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        
        this.setAlwaysOnTop(false);
        
        try {
               if(csvFile.length()>0)
               {
                //adiciona nomes da cidade/região
                cidade = jTextField2.getText();
                   
                this.setAlwaysOnTop(false);

                Vector<Oferta> ofertas = new Vector<Oferta>();

                BufferedReader br = new BufferedReader(new FileReader(csvFile));

                while ((line = br.readLine()) != null) {
                    // separando os campos
                    String[] country = line.split(cvsSplitBy);
                    //System.out.println(line);

                    if (country[5].length() != 0) 
                    {
                       //System.out.println("+ "+country[5]);

                        boolean existe = false;

                        for (int i = 0; i < ofertas.size(); i++) {
                            if (ofertas.get(i).getNome().equals(country[5])) {
                                existe = true;
                            }
                        }

                        if (existe == false) {
                            Oferta o = new Oferta();
                            o.setNome(country[5]);
                            ofertas.add(o);
                        }

                        for (int i = 0; i < ofertas.size(); i++) {
                            if (ofertas.get(i).getNome().equals(country[5])) {
                                ofertas.get(i).setQuantidade(ofertas.get(i).getQuantidade() + 1);
                            }
                            //System.out.println(ofertas.get(i).getNome()+" : "+ofertas.get(i).getQuantidade());
                        }

                    }
                }

               //====================================================================

                DefaultPieDataset dataset = new DefaultPieDataset( );
                DefaultCategoryDataset dataset2 = new DefaultCategoryDataset( ); 
                DefaultPieDataset dataset3 = new DefaultPieDataset( );
          
                for(int i=0;i<ofertas.size();i++)
                {
                    System.out.println(ofertas.get(i).getNome()+" : "+ofertas.get(i).getQuantidade());
                    dataset.setValue( ofertas.get(i).getNome()+" : "+ofertas.get(i).getQuantidade(), ofertas.get(i).getQuantidade() ); 
                    dataset2.addValue( ofertas.get(i).getQuantidade() , ofertas.get(i).getNome(), cidade);  
                    dataset3.setValue( ofertas.get(i).getNome()+" : "+ofertas.get(i).getQuantidade(), ofertas.get(i).getQuantidade() ); 
                }
                
                int width = 1280;   /* Width of the image */
                int height = 720;  /* Height of the image */ 
                
                
                JFreeChart chart = ChartFactory.createPieChart(
                    "Ofertas em "+cidade,   // chart title
                    dataset,          // data
                    true,             // include legend
                    true,
                    false);
         
                File pieChart = new File( "PieChart.jpeg" ); 
                ChartUtilities.saveChartAsJPEG( pieChart , chart , width , height );
                
                //============================

                JFreeChart barChart = ChartFactory.createBarChart(
                    "Ofertas em "+cidade, 
                    "Bairro", "Ofertas", 
                    dataset2,PlotOrientation.VERTICAL, 
                    true, true, false);
         
                File BarChart = new File( "BarChart.jpeg" ); 
                ChartUtilities.saveChartAsJPEG( BarChart , barChart , width , height );
      
                //============================
        
                JFreeChart chart3 = ChartFactory.createPieChart3D( 
                    "Ofertas em "+cidade ,  // chart title                   
                    dataset3 ,         // data 
                    true ,            // include legend                   
                    true, 
                    false);

                PiePlot3D plot = ( PiePlot3D ) chart3.getPlot( );  
                plot.setStartAngle( 270 );                      
                plot.setInteriorGap( 0.02 );                                         
                File pieChart3D = new File( "pie_Chart3D.jpeg" );                           
                ChartUtilities.saveChartAsJPEG( pieChart3D , chart3 , width , height );
  
                
                //...
                 JOptionPane.showMessageDialog(this, "Graficos jerados com sucesso.", "Ateção.", JOptionPane.WARNING_MESSAGE);
                
               }
               else
               {
                   JOptionPane.showMessageDialog(this, "Caregue antes o arquivo .csv.", "Ateção.", JOptionPane.WARNING_MESSAGE);
               }
               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Os graficos não pureram ser gerados.", "Ateção.", JOptionPane.WARNING_MESSAGE);
        }
        
        this.setAlwaysOnTop(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
          try
          {
        
            //Create a file chooser
            final JFileChooser fc = new JFileChooser();

            //In response to a button click:
            int returnVal = fc.showOpenDialog(this);
            
            if (returnVal == JFileChooser.APPROVE_OPTION) 
            {
                
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            System.out.println("Opening: " + file.getName() );
            System.out.println(file.getCanonicalPath());
            
            csvFile = file.getCanonicalPath();
            
            jTextField1.setText(csvFile);
            
            this.setAlwaysOnTop(true);
        
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"O arquvo não pode ser lido.","Ateção.", JOptionPane.WARNING_MESSAGE);
        }
            
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        
      //==================================================
      //Facebook posts
      
       String accessToken = jTextField3.getText();
             
             
     FacebookClient fbClient = new DefaultFacebookClient(accessToken);
      
     User user = fbClient.fetchObject("me", User.class);
        
     System.out.println(user.getName());
     //System.out.println(user.getLanguages().get(0).getName());
     
     AccessToken exAccessToken = fbClient.obtainExtendedAccessToken("2006680602921909", "cdc27b276d5469ea3ad768ac0b9065c4");
     
     System.out.println(exAccessToken.getAccessToken());
     System.out.println(exAccessToken.getExpires());
     
       // Connection<Post> result = fbClient.fetchConnection("me/feed",  Post.class);
     
MyPhotoTag myTag = new MyPhotoTag();
// fill myTag here
ArrayList<MyPhotoTag> myTagList = new ArrayList<MyPhotoTag>();

myTag.setTagUid(jTextField4.getText());
myTag.setTagText(jTextField5.getText());
myTag.setX(0.0);
myTag.setY(0.0);

myTagList.add(myTag);
     

     FileInputStream fis;
        try {
            fis = new FileInputStream(new File("PieChart.jpeg"));
            
            FacebookType  response =  fbClient.publish("me/photos", FacebookType.class, 
                                    BinaryAttachment.with("PieChart.jpeg", fis),
                                    Parameter.with("message", jTextArea1.getText()),
             Parameter.with("tags",myTagList)
                                            );
     System.out.println("fb.com/"+response.getId());
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
     
//     
//    //===============
//     
//     fis = new FileInputStream(new File("pie_Chart3D.jpeg"));
//     
//     response =  fbClient.publish("me/photos", FacebookType.class, 
//                                    BinaryAttachment.with("pie_Chart3D.jpeg", fis),
//                                    Parameter.with("message", "Grafico pie_Chart3D. Com as ofertas de 12 May, 2017 disponiveis nos bairros de Antwerp, Flemish Region e Belgium. "
//                                            + "Dados disponiveis em: http://data.insideairbnb.com/belgium/vlg/antwerp/2017-05-12/visualisations/listings.csv"),
//             Parameter.with("tags",myTagList)
//                                            );
//     System.out.println("fb.com/"+response.getId());
// 
//     
//     //===============
//     
//     fis = new FileInputStream(new File("BarChart.jpeg"));
//     
//     response =  fbClient.publish("me/photos", FacebookType.class, 
//                                    BinaryAttachment.with("BarChart.jpeg", fis),
//                                    Parameter.with("message", "Grafico BarChart. Com as ofertas de 12 May, 2017 disponiveis nos bairros de Antwerp, Flemish Region e Belgium. "
//                                            + "Dados disponiveis em: http://data.insideairbnb.com/belgium/vlg/antwerp/2017-05-12/visualisations/listings.csv"),
//                                    Parameter.with("tags",myTagList)
//                                            );
//     System.out.println("fb.com/"+response.getId());
//        
        
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
